num1=int(input("Enter First Number :"))
num2=int(input("Enter second Number :"))
print("Addition of 2 Numbers:",(num1+num2))
print("Substraction of 2 Numbers:",(num1-num2))
print("Multiplication of 2 Numbers:",(num1*num2))
print("Division of 2 Numbers:",(num1/num2))
